'use client'
import './globals.css'
import { Inter } from 'next/font/google'
import { store } from '../store/store'
import { Provider } from 'react-redux'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Provider store={store}>
        <body className={inter.className}>{children}</body>
      </Provider>
    </html>
  )
}


addPerson: (state, action) => {
  const { ef, firstname, lastname, birthday, nationality, idcard,
    gender, phonenumber, passport, salary, phone } = action.payload;

  const newPerson = {
    ef, firstname, lastname, birthday, nationality, idcard,
    gender, phonenumber, passport, salary, phone
  };

  // สร้าง state ใหม่โดยรวม newPerson เข้าไปใน array ของบุคคล
  const newState = [...state, newPerson];

  // อัปเดต Local Storage โดยอ่านข้อมูลเก่าจาก Local Storage และรวมกับ newState
  const updatedLocalStorageData = JSON.parse(localStorage.getItem('persons')) || [];
  updatedLocalStorageData.push(newPerson);
  localStorage.setItem('persons', JSON.stringify(updatedLocalStorageData));

  return newState;
}